---
- hosts: all
  sudo: yes
  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=86400
    - name: Add repository for PHP 7.1.
      apt_repository: repo='ppa:ondrej/php'
  roles:
    # Absolutely needed roles
    - geerlingguy.git
    - geerlingguy.postfix
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.php-mysql
    - geerlingguy.phpmyadmin
    - geerlingguy.composer
    # Conditional roles
    - { role: geerlingguy.php-xdebug, when: '"xdebug" in installed_extras' }
    - { role: geerlingguy.daemonize, when: '"mailhog" in installed_extras' }
    - { role: geerlingguy.mailhog, when: '"mailhog" in installed_extras' }
    - { role: geerlingguy.nodejs, when: '"nodejs" in installed_extras' }
    - { role: geerlingguy.ruby, when: '"ruby" in installed_extras' }
    - { role: geerlingguy.firewall, when: '"iptables" in installed_extras' }
